copyright: Copyright &copy; 2025 W Anders
edit_uri: edit/master/docs
extra_css:
- stylesheets/extra.css
markdown_extensions: 
- admonition
- attr_list
- footnotes
- pymdownx.betterem:
    smart_enable: all
- pymdownx.caret
- pymdownx.critic
- pymdownx.details
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
- pymdownx.highlight
- pymdownx.inlinehilite
- pymdownx.keys
- pymdownx.mark
- pymdownx.tilde
- pymdownx.smartsymbols
- pymdownx.snippets:
    url_download: true
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.tasklist:
    custom_checkbox: true
- tables
- toc:
    permalink: true
nav:
- Welcome: index.md
- Root CA:
  - root_ca/index.md
  - (Optional) DNS: root_ca/dns/index.md
  - CA Template: root_ca/ca_template/index.md
  - Github App: root_ca/github_app/index.md
  - Bootstrap CA: root_ca/bootstrap.md
  - Database Security: root_ca/database_security/index.md
  - Deploy and Wrap Up: root_ca/deploy_wrap_up.md
  - CA Operation: root_ca/operation.md
- Hardware:
  - hardware/index.md
- Software:
  - software/index.md
- Integrations:
  - integrations/index.md
plugins:
- git-revision-date-localized:
    enable_creation_date: true
- search
repo_name: doubleu-labs/docs
repo_url: https://github.com/doubleu-labs/docs
site_author: W Anders <w@doubleu.codes>
site_description: Doubleu Labs
site_name: Doubleu Labs
site_url: https://labs.doubleu.codes/docs
theme:
  favicon: img/favicon.ico
  features:
  - content.code.copy
  - content.tabs.link
  - header.autohide
  - navigation.instant
  - navigation.tabs
  - navigation.top
  - search.highligh
  - search.suggest
  - toc.integrate
  font: false
  icon:
    repo: fontawesome/brands/github
  language: en
  logo: https://avatars.githubusercontent.com/u/127368282
  name: material
  palette:
  - scheme: default
    media: "(prefers-color-scheme: light)"
    primary: custom
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  - scheme: slate
    media: "(prefers-color-scheme: dark)"
    primary: custom
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
