copyright: Copyright &copy; 2024 W Anders
edit_uri: edit/master/docs
extra_css:
- stylesheets/extra.css
markdown_extensions: 
- admonition
- attr_list
- footnotes
- pymdownx.betterem:
    smart_enable: all
- pymdownx.caret
- pymdownx.critic
- pymdownx.details
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
- pymdownx.highlight
- pymdownx.inlinehilite
- pymdownx.keys
- pymdownx.mark
- pymdownx.tilde
- pymdownx.smartsymbols
- pymdownx.snippets:
    url_download: true
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.tasklist:
    custom_checkbox: true
- tables
- toc:
    permalink: true
nav:
- Welcome: index.md
- Bootstrap:
  - bootstrap/index.md
  - 00 - Rundown:
    - Hardware: bootstrap/00-rundown/hardware.md
    - IPAM: bootstrap/00-rundown/ipam.md
  - 01 - Root CA:
    - Getting Started: bootstrap/01-root-ca/getting_started.md
    - Block Storage: bootstrap/01-root-ca/block.md
    - KDBX Storage: bootstrap/01-root-ca/kdbx.md
    - Initialize Root CA: bootstrap/01-root-ca/initialize.md
    - Publish CA Files: bootstrap/01-root-ca/publish.md
    - Operation: bootstrap/01-root-ca/operation.md
  - 02 - Prepare Sub CA: bootstrap/02-prep-sub-ca.md
  - 03 - Prepare to go Offline: bootstrap/03-prep-offline.md
  - Offline Setup:
    - 04 - OOBM Srv: bootstrap/offline-setup/04-oobm-srv.md
    - 05 - Switch Setup: bootstrap/offline-setup/05-switch-setup.md
plugins:
- git-revision-date-localized:
    enable_creation_date: true
- search
repo_name: doubleu-labs/docs
repo_url: https://github.com/doubleu-labs/docs
site_author: W Anders <w@doubleu.codes>
site_description: Doubleu Labs Documentation
site_name: Doubleu Labs Documentation
site_url: https://labs.doubleu.codes/docs
theme:
  favicon: img/favicon.ico
  features:
  - content.code.copy
  - content.tabs.link
  - header.autohide
  - navigation.indexes
  - navigation.instant
  - navigation.tabs
  - navigation.top
  - search.highligh
  - search.suggest
  - toc.integrate
  font: false
  icon:
    repo: fontawesome/brands/github
  language: en
  logo: https://avatars.githubusercontent.com/u/127368282
  name: material
  palette:
  - scheme: default
    media: "(prefers-color-scheme: light)"
    primary: custom
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  - scheme: slate
    media: "(prefers-color-scheme: dark)"
    primary: custom
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
